# Generated by Django 2.2.13 on 2022-10-15 01:45

from django.db import migrations, models
import pandas as pd

from users.models import Rol

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('names', models.CharField(blank=True, max_length=200, null=True, verbose_name='Names')),
                ('lastnames', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lastnames')),
                ('phone', models.CharField(blank=True, max_length=9, null=True, verbose_name='Phone')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
