# Generated by Django 2.2.13 on 2022-10-15 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221014_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='its_staff',
            field=models.BooleanField(default=False),
        ),
    ]
