# Generated by Django 3.2 on 2022-10-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='its_active',
            field=models.BooleanField(default=True),
        ),
    ]
