# Generated by Django 3.2 on 2022-10-17 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rol_its_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='its_staff',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.rol'),
        ),
    ]
